apiVersion: v1
kind: Service
metadata:
  name: nginx              # will inherit suffixes/labels
  labels:
    app: nginx
spec:
  type: LoadBalancer       # exposed externally on most clouds
  selector:
    app: nginx
  ports:
  - port: 80               # service port
    targetPort: 80         # containerPort
